"""create safe_route schema and initial tables

Revision ID: 8c899f3e4507
Revises:
Create Date: 2026-03-31 19:19:39.112267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c899f3e4507"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "CREATE SCHEMA IF NOT EXISTS safe_route"
    )  # will create the safe_route schema if it doesn't exist
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "EDITOR", "REPORTER", name="userrole"),
            nullable=False,
        ),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="safe_route",
    )
    op.create_table(
        "location",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("town", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="safe_route",
    )
    op.create_table(
        "report",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reporter_id", sa.UUID(), nullable=True),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("approver_id", sa.UUID(), nullable=True),
        sa.Column("reference_no", sa.String(length=12), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "UNDER_REVIEW", "APPROVED", "RESOLVED", name="reportstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "report_type",
            sa.Enum(
                "ROBBERY",
                "ASSAULT_VIOLENCE",
                "HARASSMENT",
                "ROADBLOCKS",
                "OTHER",
                name="reporttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="severitylevel"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("incident_at", sa.DateTime(), nullable=False),
        sa.Column("approval_date", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["safe_route.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["safe_route.location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["safe_route.app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference_no"),
        schema="safe_route",
    )
    op.create_index(
        "idx_report_incident_at",
        "report",
        ["incident_at"],
        unique=False,
        schema="safe_route",
    )
    op.create_index(
        "idx_report_location_id",
        "report",
        ["location_id"],
        unique=False,
        schema="safe_route",
    )
    op.create_index(
        "idx_report_reference_no",
        "report",
        ["reference_no"],
        unique=False,
        schema="safe_route",
    )
    op.create_index(
        "idx_report_reporter_id",
        "report",
        ["reporter_id"],
        unique=False,
        schema="safe_route",
    )
    op.create_index(
        "idx_report_severity", "report", ["severity"], unique=False, schema="safe_route"
    )
    op.create_index(
        "idx_report_status", "report", ["status"], unique=False, schema="safe_route"
    )
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column(
            "type", sa.Enum("IMAGE", "VIDEO", "AUDIO", name="mediatype"), nullable=False
        ),
        sa.Column("media_link", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["safe_route.report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="safe_route",
    )
    op.create_table(
        "report_audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_type",
            sa.Enum("USER", "ANONYMOUS", "SYSTEM", name="actortype"),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "CREATED",
                "STATUS_CHANGED",
                "SEVERITY_CHANGED",
                "ASSIGNED",
                "APPROVED",
                "DESCRIPTION_EDITED",
                "MEDIA_ADDED",
                "MEDIA_REMOVED",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["safe_route.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["safe_route.report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="safe_route",
    )
    op.create_index(
        "idx_audit_log_actor_id",
        "report_audit_log",
        ["actor_id"],
        unique=False,
        schema="safe_route",
    )
    op.create_index(
        "idx_audit_log_created_at",
        "report_audit_log",
        ["created_at"],
        unique=False,
        schema="safe_route",
    )
    op.create_index(
        "idx_audit_log_report_id",
        "report_audit_log",
        ["report_id"],
        unique=False,
        schema="safe_route",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP SCHEMA IF EXISTS safe_route CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_audit_log_report_id", table_name="report_audit_log", schema="safe_route"
    )
    op.drop_index(
        "idx_audit_log_created_at", table_name="report_audit_log", schema="safe_route"
    )
    op.drop_index(
        "idx_audit_log_actor_id", table_name="report_audit_log", schema="safe_route"
    )
    op.drop_table("report_audit_log", schema="safe_route")
    op.drop_table("media", schema="safe_route")
    op.drop_index("idx_report_status", table_name="report", schema="safe_route")
    op.drop_index("idx_report_severity", table_name="report", schema="safe_route")
    op.drop_index("idx_report_reporter_id", table_name="report", schema="safe_route")
    op.drop_index("idx_report_reference_no", table_name="report", schema="safe_route")
    op.drop_index("idx_report_location_id", table_name="report", schema="safe_route")
    op.drop_index("idx_report_incident_at", table_name="report", schema="safe_route")
    op.drop_table("report", schema="safe_route")
    op.drop_table("location", schema="safe_route")
    op.drop_table("app_user", schema="safe_route")
    # ### end Alembic commands ###
